version: '3.1'

services:
  db-postgres:
    image: "postgres"
    container_name: "microservicios-postgres"
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sasa
      POSTGRES_DB: db_springboot_cloud
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
  
  postgres-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "klint_f@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - db-postgres
    networks:
      - postgres-compose-network    
networks: 
  postgres-compose-network:
    driver: bridge